### ISSUE TITLE
Where do I get the JSON file? 

### ISSUE THREAD

**Issue by Anubhavixigo** [Zrce/Google-Discover-API-in-Python#2]
Hi Tobias, 

Tried out your Collab notebook. Getting this error when running the code. 

I didn't understand how to get the JSON file. Wasn't mentioned anywhere in the medium article. 

<img width="895" alt="Screen Shot 2021-11-10 at 5 21 31 PM" src="https://user-images.githubusercontent.com/94052655/141108229-3f1b8fab-a73c-4e3f-a4cb-11098b7f60b3.png">

**Comment by Anubhavixigo** [comment]
Hi @Zrce

Figured out the last issue. We had to generate a JSON file from the service account in Google cloud? Pardon me. I am new to the world of coding. I have done that. So that issue is resolved. However, I am facing a new issue. Can you help me out with this one? 
<img width="915" alt="Screen Shot 2021-11-10 at 5 48 57 PM" src="https://user-images.githubusercontent.com/94052655/141112949-df21c9f1-4516-4128-afbc-ce4a50869734.png">

<img width="880" alt="Screen Shot 2021-11-10 at 5 55 29 PM" src="https://user-images.githubusercontent.com/94052655/141112995-1b89bded-a7c3-423c-b94d-321ad555941d.png">


<img width="915" alt="Screen Shot 2021-11-10 at 5 48 57 PM" src="https://user-images.githubusercontent.com/94052655/141112985-71f1c264-c508-4c38-be85-2b093fc6b8c7.png">

Would really appreciate if you can help out.

**Comment by Zrce** [comment]
Try to go to Google Search Console and select your property. Go to users and permissions + then add the service account email from within the json

**Comment by Anubhavixigo** [comment]
It worked! Thank you!
